name: CI with Gradle and Cucumber

on: [push]
    
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew test
